# Generated by Django 5.1.6 on 2025-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], default='Laptop', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='domain_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='mouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='product_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default='xxx', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='user_company',
            field=models.CharField(default='BAK', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
